[workspace]
members = [
    "resolvers/manatee-primary-resolver",
    "resolvers/static-resolver",
    "resolvers/dns-resolver",
    "connections/postgres-connection",
    "connections/tcp-stream-connection",
    "cueball",
    "tools/manatee-echo-resolver",
]
